/**
 * MCG Pro Shop — the golf ball wall.
 *
 * Every item here is backed by real PGA TOUR Superstore product photography: the shots
 * were pulled per product, processed, and are served from the `mcg-shop-images` staticDir
 * at `mcg-shop-images/balls/<file>`. The manifest that drives this file is
 * `images/mcg-shop/balls-index.json` (27 products, 82 images) — one entry per product,
 * carrying the real product title, the real product URL and the processed filenames.
 * Per-image provenance (source page plus the original CDN URL for each shot) lives in
 * `references/091026/pos-item-imagery/PGA TOUR Superstore Ball Imagery/<folder>/source.txt`.
 *
 * Because the photography is multi-angle, these products are the one part of the catalog
 * where the detail page's thumbnail rail has real work to do — hence `gallery`, which the
 * hand-built entries in `../shop-catalog` leave unset.
 *
 * Names, prices, ratings, stock and copy are ours, not the retailer's, and are set for a
 * county muni: tour dozens around $50–$55, sleeves at roughly a quarter of the box, value
 * dozens in the low twenties, recycled 24-packs cheaper still, and two range buckets at
 * counter prices. Slugs are the manifest slugs, so nothing here collides with the
 * hand-built ball entries in `../shop-catalog`.
 */
import type { ShopCategoryId, ShopColor, ShopProduct } from "@/components/mcg/shop-catalog";
import { asset } from "@/utils/asset";

/* ------------------------------------------------------------------ */
/* Imagery helpers                                                     */
/* ------------------------------------------------------------------ */

/** Processed PGA TOUR Superstore ball photography, served from `images/mcg-shop/balls`. */
const BALL = (file: string) => asset(`mcg-shop-images/balls/${file}`);
const LOGO = (file: string) => asset(`store-images/logos/${file}`);

/** The five ball brands the wall actually carries, plus our own stamped ball. */
const BRAND = {
    titleist: { name: "Titleist", logo: LOGO("logo-Titleist-5191ae6257.webp") },
    callaway: { name: "Callaway", logo: LOGO("logo-Callaway-1361699423.webp") },
    taylormade: { name: "TaylorMade", logo: LOGO("logo-TaylorMade-2f17ac4849.webp") },
    srixon: { name: "Srixon", logo: LOGO("logo-Srixon-8c85331b79.webp") },
    bridgestone: { name: "Bridgestone", logo: LOGO("logo-Bridgestone-f255386e56.webp") },
    mcg: { name: "MCG" },
} satisfies Record<string, { name: string; logo?: string }>;

/** Ball colourways. Swatches are literal hex because they depict the ball, not the UI. */
const C = {
    white: { name: "White", swatch: "#F7F7F5" },
    yellow: { name: "Optic yellow", swatch: "#E7D14B" },
    red: { name: "Matte red", swatch: "#C2453C" },
} satisfies Record<string, ShopColor>;

/* ------------------------------------------------------------------ */
/* Pack shapes                                                         */
/* ------------------------------------------------------------------ */

/** Balls and buckets only — the two categories anything in this file can land in. */
const BALLS: ShopCategoryId = "balls";
const ACCESSORIES: ShopCategoryId = "accessories";

const DOZEN = ["Dozen (12)"];
const SLEEVE = ["Sleeve (3)"];
const PACK_24 = ["24 pack"];

/* ------------------------------------------------------------------ */
/* The wall                                                            */
/* ------------------------------------------------------------------ */

export const BALL_PRODUCTS: ShopProduct[] = [
/* ---------------------------- Titleist ----------------------------- */
    {
        slug: "titleist-pro-v1-box",
        name: "Titleist Pro V1 (2025)",
        category: BALLS,
        brand: BRAND.titleist.name,
        brandLogo: BRAND.titleist.logo,
        image: BALL("titleist-pro-v1-box-1.jpg"),
        gallery: ["titleist-pro-v1-box-1.jpg", "titleist-pro-v1-box-2.jpg", "titleist-pro-v1-box-3.jpg", "titleist-pro-v1-box-4.jpg"].map(BALL),
        price: 55,
        rating: 4.9,
        reviews: 412,
        inStock: true,
        blurb: "The ball the county amateur field plays: soft cast urethane, penetrating flight, and a wedge that checks on the second hop.",
        details: [
            "Dozen",
            "Three-piece, 2.0 ZG process core",
            "Cast urethane elastomer cover, 388 tetrahedral dimples",
            "Roughly 87 compression — mid flight, high greenside spin",
            "Suits swing speeds from 90 mph up",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow],
    },
    {
        slug: "titleist-pro-v1x-box",
        name: "Titleist Pro V1x (2025)",
        category: BALLS,
        brand: BRAND.titleist.name,
        brandLogo: BRAND.titleist.logo,
        image: BALL("titleist-pro-v1x-box-1.jpg"),
        gallery: ["titleist-pro-v1x-box-1.jpg", "titleist-pro-v1x-box-2.jpg", "titleist-pro-v1x-box-3.jpg", "titleist-pro-v1x-box-4.jpg"].map(BALL),
        price: 55,
        rating: 4.8,
        reviews: 336,
        inStock: true,
        blurb: "The higher, firmer Pro V1 — four pieces and a dual core, for players who want more iron spin and a steeper descent into our smaller greens.",
        details: [
            "Dozen",
            "Four-piece, dual core construction",
            "Cast urethane cover, 348 tetrahedral dimples",
            "Roughly 97 compression — firmer feel than Pro V1",
            "Higher flight, more long-iron spin, steeper stopping angle",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow],
    },
    {
        slug: "titleist-pro-v1-sleeve",
        name: "Titleist Pro V1 — Sleeve of 3",
        category: BALLS,
        brand: BRAND.titleist.name,
        brandLogo: BRAND.titleist.logo,
        image: BALL("titleist-pro-v1-sleeve-1.jpg"),
        gallery: ["titleist-pro-v1-sleeve-1.jpg", "titleist-pro-v1-sleeve-2.jpg", "titleist-pro-v1-sleeve-3.jpg", "titleist-pro-v1-sleeve-4.jpg"].map(BALL),
        price: 16,
        rating: 4.8,
        reviews: 148,
        inStock: true,
        blurb: "Three Pro V1s for the round you're already late for — the counter sleeve, priced a quarter of the box.",
        details: ["Sleeve of 3", "Same 2025 Pro V1 as the dozen", "Cast urethane elastomer cover", "Stocked at every counter, including the starter huts"],
        sizes: SLEEVE,
        colors: [C.white],
    },
    {
        slug: "titleist-pro-v1x-sleeve",
        name: "Titleist Pro V1x — Sleeve of 3",
        category: BALLS,
        brand: BRAND.titleist.name,
        brandLogo: BRAND.titleist.logo,
        image: BALL("titleist-pro-v1x-sleeve-1.jpg"),
        gallery: ["titleist-pro-v1x-sleeve-1.jpg", "titleist-pro-v1x-sleeve-2.jpg", "titleist-pro-v1x-sleeve-3.jpg", "titleist-pro-v1x-sleeve-4.jpg"].map(BALL),
        price: 16,
        rating: 4.7,
        reviews: 121,
        inStock: true,
        blurb: "A three-ball sleeve of the firmer, higher-flying Pro V1x — enough to try it for nine before committing to a box.",
        details: ["Sleeve of 3", "Same 2025 Pro V1x as the dozen", "Four-piece, dual core", "Firmer feel, higher flight than Pro V1"],
        sizes: SLEEVE,
        colors: [C.white],
    },
    {
        slug: "titleist-avx-box",
        name: "Titleist AVX (2026)",
        category: BALLS,
        brand: BRAND.titleist.name,
        brandLogo: BRAND.titleist.logo,
        image: BALL("titleist-avx-box-1.jpg"),
        gallery: ["titleist-avx-box-1.jpg", "titleist-avx-box-2.jpg"].map(BALL),
        price: 52,
        rating: 4.6,
        reviews: 164,
        inStock: true,
        blurb: "The softest urethane ball Titleist makes, and the lowest-flying — a genuine help into the wind off the ridge at Little Bennett.",
        details: [
            "Dozen",
            "Three-piece with a high-speed GRN41 core",
            "Thermoset urethane cover, 348 catenary dimples",
            "Roughly 80 compression — the softest feel of the Titleist tour line",
            "Lower flight and lower long-game spin; keeps the urethane short-game bite",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow],
    },
    {
        slug: "titleist-avx-sleeve",
        name: "Titleist AVX — Sleeve of 3",
        category: BALLS,
        brand: BRAND.titleist.name,
        brandLogo: BRAND.titleist.logo,
        image: BALL("titleist-avx-sleeve-1.jpg"),
        gallery: ["titleist-avx-sleeve-1.jpg", "titleist-avx-sleeve-2.jpg"].map(BALL),
        price: 15,
        rating: 4.5,
        reviews: 73,
        inStock: true,
        blurb: "Three AVX, for the player who suspects a lower, softer ball is the fix and wants a nine-hole trial before the dozen.",
        details: ["Sleeve of 3", "Same 2026 AVX as the dozen", "Thermoset urethane cover", "Low flight, soft feel, low long-game spin"],
        sizes: SLEEVE,
        colors: [C.white],
    },
    {
        slug: "titleist-tour-speed-box",
        name: "Titleist Tour Speed — Reload 24-Pack",
        category: BALLS,
        brand: BRAND.titleist.name,
        brandLogo: BRAND.titleist.logo,
        image: BALL("titleist-tour-speed-box-1.jpg"),
        gallery: ["titleist-tour-speed-box-1.jpg"].map(BALL),
        price: 42,
        compareAt: 55,
        rating: 4.3,
        reviews: 207,
        inStock: true,
        blurb: "Twenty-four recovered Tour Speeds graded near mint — urethane-quality short game at range-ball money, and they look new in the box.",
        details: [
            "24 balls, recovered and graded Near Mint",
            "Three-piece with a TPU cover — between TruFeel and Pro V1 in feel",
            "Cosmetic marks possible; play characteristics intact",
            "White only, no player-number sorting",
            "The best value on the wall for a two-round-a-week player",
        ],
        sizes: PACK_24,
        colors: [C.white],
    },
    {
        slug: "titleist-trufeel-box",
        name: "Titleist TruFeel (2026)",
        category: BALLS,
        brand: BRAND.titleist.name,
        brandLogo: BRAND.titleist.logo,
        image: BALL("titleist-trufeel-box-1.jpg"),
        gallery: ["titleist-trufeel-box-1.jpg", "titleist-trufeel-box-2.jpg"].map(BALL),
        price: 28,
        rating: 4.7,
        reviews: 289,
        inStock: true,
        blurb: "The softest ball Titleist makes and the box that moves fastest here — a Titleist script for under thirty dollars.",
        details: [
            "Dozen",
            "Two-piece, large TruTouch core",
            "TruFlex ionomer cover, 376 tetrahedral dimples",
            "Around 60 compression — very soft off the putter face",
            "Built for moderate swing speeds; distance without the tour-ball price",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow],
    },

    /* ---------------------------- Callaway ----------------------------- */
    {
        slug: "callaway-chrome-soft-box",
        name: "Callaway Chrome Soft (2026)",
        category: BALLS,
        brand: BRAND.callaway.name,
        brandLogo: BRAND.callaway.logo,
        image: BALL("callaway-chrome-soft-box-1.jpg"),
        gallery: ["callaway-chrome-soft-box-1.jpg", "callaway-chrome-soft-box-2.jpg", "callaway-chrome-soft-box-3.jpg"].map(BALL),
        price: 50,
        rating: 4.7,
        reviews: 298,
        inStock: true,
        blurb: "A tour ball built for the swing speeds most of our field actually has — soft at 75 compression, and it still spins on a half wedge.",
        details: [
            "Dozen",
            "Four-piece with a Hyper Elastic SoftFast core",
            "Cast urethane cover",
            "Around 75 compression — softer than most tour balls",
            "Best under 100 mph driver speed; Triple Track alignment available",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow],
    },
    {
        slug: "callaway-chrome-soft-sleeve",
        name: "Callaway Chrome Soft — Sleeve of 3",
        category: BALLS,
        brand: BRAND.callaway.name,
        brandLogo: BRAND.callaway.logo,
        image: BALL("callaway-chrome-soft-sleeve-1.jpg"),
        gallery: ["callaway-chrome-soft-sleeve-1.jpg", "callaway-chrome-soft-sleeve-2.jpg", "callaway-chrome-soft-sleeve-3.jpg"].map(BALL),
        price: 14,
        rating: 4.6,
        reviews: 96,
        inStock: true,
        blurb: "Three Chrome Softs at the counter — the sleeve we sell most of on Saturday mornings at Needwood.",
        details: ["Sleeve of 3", "Same 2026 Chrome Soft as the dozen", "Cast urethane cover", "Soft feel, full greenside spin"],
        sizes: SLEEVE,
        colors: [C.white],
    },
    {
        slug: "callaway-chrome-soft-x-box",
        name: "Callaway Chrome Soft X — Reload 24-Pack",
        category: BALLS,
        brand: BRAND.callaway.name,
        brandLogo: BRAND.callaway.logo,
        image: BALL("callaway-chrome-soft-x-box-1.jpg"),
        gallery: ["callaway-chrome-soft-x-box-1.jpg"].map(BALL),
        price: 36,
        compareAt: 48,
        rating: 4.2,
        reviews: 134,
        inStock: true,
        blurb: "Two dozen recovered Chrome Soft X at good grade — a firmer, more workable tour ball for the price of a value dozen and a half.",
        details: [
            "24 balls, recovered and graded Good",
            "Four-piece, firmer than standard Chrome Soft at about 90 compression",
            "Cast urethane cover; lower driver spin, more workable flight",
            "Visible cosmetic wear on some balls — priced for it",
            "Popular with the winter league, who lose a few",
        ],
        sizes: PACK_24,
        colors: [C.white],
    },
    {
        slug: "callaway-supersoft-box",
        name: "Callaway Supersoft (2025)",
        category: BALLS,
        brand: BRAND.callaway.name,
        brandLogo: BRAND.callaway.logo,
        image: BALL("callaway-supersoft-box-1.jpg"),
        gallery: ["callaway-supersoft-box-1.jpg", "callaway-supersoft-box-2.jpg", "callaway-supersoft-box-3.jpg", "callaway-supersoft-box-4.jpg"].map(BALL),
        price: 27,
        rating: 4.5,
        reviews: 361,
        inStock: true,
        blurb: "Thirty-eight compression and a hybrid cover — the low-spin dozen that straightens out a slice more than any lesson we can sell you.",
        details: [
            "Dozen",
            "Two-piece with a Hyper Elastic SoftFast core",
            "Hybrid ionomer cover, HEX aerodynamics",
            "38 compression — the softest thing on the wall",
            "Low spin and high launch; made for slower swing speeds",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow, C.red],
    },
    {
        slug: "callaway-warbird-box",
        name: "Callaway Warbird (2025)",
        category: BALLS,
        brand: BRAND.callaway.name,
        brandLogo: BRAND.callaway.logo,
        image: BALL("callaway-warbird-box-1.jpg"),
        gallery: ["callaway-warbird-box-1.jpg", "callaway-warbird-box-2.jpg", "callaway-warbird-box-3.jpg", "callaway-warbird-box-4.jpg"].map(BALL),
        price: 23,
        rating: 4.2,
        reviews: 244,
        inStock: true,
        blurb: "A big, hot core in a hard ionomer shell: all carry, no subtlety, and the cheapest new Callaway dozen we stock.",
        details: [
            "Dozen",
            "Two-piece with an oversized high-energy core",
            "Ionomer cover — durable through a cart path bounce",
            "High launch, low spin, long off the tee",
            "Value dozen; short-game spin is not what you're buying",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow],
    },

    /* --------------------------- TaylorMade ---------------------------- */
    {
        slug: "taylormade-tp5-box",
        name: "TaylorMade TP5 (2026)",
        category: BALLS,
        brand: BRAND.taylormade.name,
        brandLogo: BRAND.taylormade.logo,
        image: BALL("taylormade-tp5-box-1.jpg"),
        gallery: ["taylormade-tp5-box-1.jpg", "taylormade-tp5-box-2.jpg", "taylormade-tp5-box-3.jpg", "taylormade-tp5-box-4.jpg"].map(BALL),
        price: 53,
        rating: 4.8,
        reviews: 276,
        inStock: true,
        blurb: "Five layers, 85 compression, and the softest tour feel TaylorMade sells — the box our staff plays.",
        details: [
            "Dozen",
            "Five-layer construction with a Speed-Layer System",
            "Cast urethane cover, Tour Flight dimple pattern",
            "85 compression — softer of the two TP5 models",
            "High spin on wedges, mid flight off the driver",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow],
    },
    {
        slug: "taylormade-tp5x-box",
        name: "TaylorMade TP5x (2026)",
        category: BALLS,
        brand: BRAND.taylormade.name,
        brandLogo: BRAND.taylormade.logo,
        image: BALL("taylormade-tp5x-box-1.jpg"),
        gallery: ["taylormade-tp5x-box-1.jpg", "taylormade-tp5x-box-2.jpg", "taylormade-tp5x-box-3.jpg", "taylormade-tp5x-box-4.jpg"].map(BALL),
        price: 53,
        rating: 4.6,
        reviews: 188,
        inStock: true,
        blurb: "The firmer, faster TP5 — higher launch and a click off the face you either love or don't.",
        details: [
            "Dozen",
            "Five-layer construction, firmer inner layers than TP5",
            "Cast urethane cover, Tour Flight dimple pattern",
            "97 compression — for faster swing speeds",
            "Higher launch and lower driver spin than TP5",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow],
    },
    {
        slug: "taylormade-tp5-sleeve",
        name: "TaylorMade TP5 — Sleeve of 3",
        category: BALLS,
        brand: BRAND.taylormade.name,
        brandLogo: BRAND.taylormade.logo,
        image: BALL("taylormade-tp5-sleeve-1.jpg"),
        gallery: ["taylormade-tp5-sleeve-1.jpg", "taylormade-tp5-sleeve-2.jpg", "taylormade-tp5-sleeve-3.jpg", "taylormade-tp5-sleeve-4.jpg"].map(BALL),
        price: 15,
        rating: 4.7,
        reviews: 88,
        inStock: true,
        blurb: "Three TP5s — the sleeve to keep in the bag for the last three holes of a match you care about.",
        details: ["Sleeve of 3", "Same 2026 TP5 as the dozen", "Five-layer, cast urethane cover", "85 compression, soft feel"],
        sizes: SLEEVE,
        colors: [C.white],
    },
    {
        slug: "taylormade-distance-box",
        name: "TaylorMade Distance+ (2025)",
        category: BALLS,
        brand: BRAND.taylormade.name,
        brandLogo: BRAND.taylormade.logo,
        image: BALL("taylormade-distance-box-1.jpg"),
        gallery: ["taylormade-distance-box-1.jpg", "taylormade-distance-box-2.jpg", "taylormade-distance-box-3.jpg", "taylormade-distance-box-4.jpg"].map(BALL),
        price: 22,
        rating: 4.3,
        reviews: 198,
        inStock: true,
        blurb: "Twenty-two dollars for twelve, and the REACT core gets more out of an 80 mph swing than anything else at the price.",
        details: [
            "Dozen",
            "Two-piece with a REACT Speed core",
            "Ionomer cover, 342 aerodynamic dimples",
            "Low driver spin for a straighter, longer ball flight",
            "Value dozen — our most common league-night box",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow],
    },
    {
        slug: "taylormade-tour-response-box",
        name: "TaylorMade Tour Response (2026)",
        category: BALLS,
        brand: BRAND.taylormade.name,
        brandLogo: BRAND.taylormade.logo,
        image: BALL("taylormade-tour-response-box-1.jpg"),
        gallery: ["taylormade-tour-response-box-1.jpg", "taylormade-tour-response-box-2.jpg"].map(BALL),
        price: 40,
        rating: 4.6,
        reviews: 231,
        inStock: true,
        blurb: "Real urethane at forty dollars — the gateway box for a player moving up from ionomer who wants the ball to stop.",
        details: [
            "Dozen",
            "Three-piece with a soft Tour Flight core",
            "100% cast urethane cover",
            "Around 70 compression — soft, muted feel",
            "The cheapest true urethane dozen we carry",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow],
    },

    /* ----------------------------- Srixon ------------------------------ */
    {
        slug: "srixon-z-star-box",
        name: "Srixon Z-Star 9 (2025)",
        category: BALLS,
        brand: BRAND.srixon.name,
        brandLogo: BRAND.srixon.logo,
        image: BALL("srixon-z-star-box-1.jpg"),
        gallery: ["srixon-z-star-box-1.jpg", "srixon-z-star-box-2.jpg", "srixon-z-star-box-3.jpg", "srixon-z-star-box-4.jpg"].map(BALL),
        price: 48,
        rating: 4.7,
        reviews: 152,
        inStock: true,
        blurb: "Srixon's Spin Skin coating grabs a wet cover better than most — worth knowing on an early tee time with dew still down.",
        details: [
            "Dozen",
            "Three-piece with a FastLayer DG core",
            "Spin Skin+ urethane cover",
            "Around 90 compression",
            "Holds spin in wet conditions; suits 95 mph driver speeds and up",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow],
    },
    {
        slug: "srixon-q-star-tour-box",
        name: "Srixon Q-Star Tour 6",
        category: BALLS,
        brand: BRAND.srixon.name,
        brandLogo: BRAND.srixon.logo,
        image: BALL("srixon-q-star-tour-box-1.jpg"),
        gallery: ["srixon-q-star-tour-box-1.jpg", "srixon-q-star-tour-box-2.jpg", "srixon-q-star-tour-box-3.jpg", "srixon-q-star-tour-box-4.jpg"].map(BALL),
        price: 38,
        rating: 4.6,
        reviews: 176,
        inStock: true,
        blurb: "Tour urethane tuned for a 90 mph swing — the ball we recommend most often to members who assume a tour ball is too much for them.",
        details: [
            "Dozen",
            "Three-piece with a FastLayer core",
            "Spin Skin urethane cover",
            "72 compression — compresses at moderate swing speeds",
            "Full greenside spin without the tour-ball firmness",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow],
    },
    {
        slug: "srixon-soft-feel-box",
        name: "Srixon Soft Feel",
        category: BALLS,
        brand: BRAND.srixon.name,
        brandLogo: BRAND.srixon.logo,
        image: BALL("srixon-soft-feel-box-1.jpg"),
        gallery: ["srixon-soft-feel-box-1.jpg", "srixon-soft-feel-box-2.jpg", "srixon-soft-feel-box-3.jpg", "srixon-soft-feel-box-4.jpg"].map(BALL),
        price: 25,
        compareAt: 30,
        rating: 4.4,
        reviews: 312,
        inStock: true,
        blurb: "Sixty compression, soft off every club, and on the rack special all season — the value dozen we reorder the most.",
        details: [
            "Dozen",
            "Two-piece with a gradient FastLayer core",
            "Soft ionomer cover, 338 Speed Dimple pattern",
            "60 compression",
            "Marked down from $30 through the season",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow],
    },

    /* --------------------------- Bridgestone --------------------------- */
    {
        slug: "bridgestone-tour-b-x-box",
        name: "Bridgestone Tour B X (2026)",
        category: BALLS,
        brand: BRAND.bridgestone.name,
        brandLogo: BRAND.bridgestone.logo,
        image: BALL("bridgestone-tour-b-x-box-1.jpg"),
        gallery: ["bridgestone-tour-b-x-box-1.jpg", "bridgestone-tour-b-x-box-2.jpg"].map(BALL),
        price: 50,
        rating: 4.5,
        reviews: 118,
        inStock: true,
        blurb: "The REACTIV iQ cover firms up on a driver strike and gives on a wedge — a distance ball and a spin ball depending on the swing.",
        details: [
            "Dozen",
            "Three-piece with a gradational core",
            "REACTIV iQ urethane cover",
            "Built for 105 mph driver speed and above",
            "Lower driver spin than Tour B XS; straighter, flatter flight",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow],
    },
    {
        slug: "bridgestone-tour-b-xs-box",
        name: "Bridgestone Tour B XS (2026)",
        category: BALLS,
        brand: BRAND.bridgestone.name,
        brandLogo: BRAND.bridgestone.logo,
        image: BALL("bridgestone-tour-b-xs-box-1.jpg"),
        gallery: ["bridgestone-tour-b-xs-box-1.jpg", "bridgestone-tour-b-xs-box-2.jpg"].map(BALL),
        price: 50,
        rating: 4.6,
        reviews: 143,
        inStock: false,
        blurb: "The softer, spinnier half of the Tour B pair. Sold through after the club championship — the next case lands in about two weeks.",
        details: [
            "Dozen",
            "Three-piece with a softer gradational core",
            "REACTIV iQ urethane cover",
            "Softer feel and more greenside spin than Tour B X",
            "Out of stock; reorder placed",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow],
    },
    {
        slug: "bridgestone-e6-box",
        name: "Bridgestone e6 Soft (2025)",
        category: BALLS,
        brand: BRAND.bridgestone.name,
        brandLogo: BRAND.bridgestone.logo,
        image: BALL("bridgestone-e6-box-1.jpg"),
        gallery: ["bridgestone-e6-box-1.jpg", "bridgestone-e6-box-2.jpg", "bridgestone-e6-box-3.jpg", "bridgestone-e6-box-4.jpg"].map(BALL),
        price: 27,
        rating: 4.4,
        reviews: 205,
        inStock: true,
        blurb: "A straight-flight two-piece that takes sidespin out of the equation — the honest answer for a player fighting a hook.",
        details: [
            "Dozen",
            "Two-piece with a soft, low-compression core",
            "Surlyn cover, Delta Wing dimple pattern",
            "Low spin for straighter flight",
            "Moderate swing speeds; white or optic yellow",
        ],
        sizes: DOZEN,
        colors: [C.white, C.yellow],
    },

    /* ------------------- MCG logo ball and range balls ------------------ */
    {
        slug: "logo-ball-single",
        name: "MCG Logo Ball — Single",
        category: BALLS,
        brand: BRAND.mcg.name,
        mcgLogo: true,
        image: BALL("logo-ball-single-1.jpg"),
        gallery: ["logo-ball-single-1.jpg", "logo-ball-single-2.jpg", "logo-ball-single-3.jpg", "logo-ball-single-4.jpg"].map(BALL),
        price: 4,
        rating: 4.8,
        reviews: 96,
        inStock: true,
        blurb: "One soft two-piece ball stamped with the county crest — the thing visitors buy at the counter instead of a postcard.",
        details: [
            "Sold as a single ball",
            "Soft two-piece, 38 compression — plays, doesn't just sit on a shelf",
            "MCG crest printed alongside the manufacturer's mark",
            "Also sold as a nine-ball course set at the Needwood counter",
        ],
        sizes: ["Single ball"],
        colors: [C.white],
    },

    /**
     * The POS button behind images 26 and 27 read "RANGE BUCKET", but the photography
     * pulled for it is a home practice net, target and hitting mat — not a bucket of
     * range balls, and both folders held the identical shot. Listing a $6 bucket
     * against a $180 net would be an obvious error in front of a client, so the two
     * entries are one product named for what the photograph actually shows. Range
     * balls are sold as punch cards in `offerings-catalog.ts`, where they belong.
     */
    {
        slug: "practice-net-mat-set",
        name: "Practice Net, Target & Mat Set",
        category: "accessories",
        brand: "Pro Shop",
        image: BALL("range-bucket-large-1.jpg"),
        price: 149,
        compareAt: 179,
        rating: 4.4,
        reviews: 96,
        inStock: true,
        blurb: "A pop-up net, aiming target, hitting mat and shag tube — the whole backyard setup in one carry bag.",
        details: [
            "Pop-up net with fibreglass frame, up on its own in under a minute",
            "Removable bullseye target sheet for aim work",
            "Turf hitting mat with a rubber tee, sits on grass or concrete",
            "Shag tube and carry bag included",
            "Rated for irons and short clubs — not a driver net",
        ],
    },
];
